---
- name: Build and deploy Docker container
  hosts: your_host
  become: yes
  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - python3-pip

    - name: Install Docker python library
      pip:
        name: docker

    - name: Build Docker image
      docker_image:
        name:  auth-server:1.0.0
        path: ./build/package/Dockerfile
        state: present

    - name: Run Docker container
      docker_container:
        name: auth-server
        image: auth-server
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
